package warrior

import (
	"slices"
	"time"
	"github.com/wowsims/classic/sim/core"
	"github.com/wowsims/classic/sim/core/stats"
)

///////////////////////////////////////////////////////////////////////////
//                            Phase 1 Item Sets - Molten Core
///////////////////////////////////////////////////////////////////////////

var ItemSetBattleGearOfMight = core.NewItemSet(core.ItemSet{
	Name: "Battlegear of Might",
	Bonuses: map[int32]core.ApplyEffect{
		// Increases the block value of your shield by 30.
		3: func(agent core.Agent) {
			character := agent.GetCharacter()
			character.AddStat(stats.BlockValue, 30)
		},
		// Gives you a 20% chance to generate an additional Rage point whenever damage is dealt to you.
		5: func(agent core.Agent) {
			warrior := agent.(WarriorAgent).GetWarrior()
			actionID := core.ActionID{SpellID: 21838}
			rageMetrics := warrior.NewRageMetrics(actionID)

			core.MakeProcTriggerAura(&warrior.Unit, core.ProcTrigger{
				ActionID:   actionID,
				Name:       "Battlegear of Might - Rage",
				Callback:   core.CallbackOnSpellHitTaken,
				ProcMask:   core.ProcMaskMelee,
				ProcChance: 0.20,
				Handler: func(sim *core.Simulation, spell *core.Spell, _ *core.SpellResult) {
					warrior.AddRage(sim, 1, rageMetrics)
				},
			})
		},
		// Increases the threat generated by Sunder Armor by 15%.
		8: func(agent core.Agent) {
			warrior := agent.(WarriorAgent).GetWarrior()
			warrior.RegisterAura(core.Aura{
				Label: "Enhanced Sunder Armor",
				OnInit: func(aura *core.Aura, sim *core.Simulation) {
					warrior.SunderArmor.ThreatMultiplier *= 1.15
					warrior.SunderArmor.FlatThreatBonus *= 1.15
				},
			})
		},
	},
})

///////////////////////////////////////////////////////////////////////////
//                            Phase 2 Item Sets - Dire Maul
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
//                            Phase 3 Item Sets - BWL
///////////////////////////////////////////////////////////////////////////

var ItemSetBattleGearOfWrath = core.NewItemSet(core.ItemSet{
	Name: "Battlegear of Wrath",
	Bonuses: map[int32]core.ApplyEffect{
		// (2) Set: 20% chance after using an offensive ability requiring rage that your next 2 offensive
		// abilities require 2 less rage to use.
		2: func(agent core.Agent) {
			warrior := agent.(WarriorAgent).GetWarrior()

			var affectedSpells []*core.Spell

			warriorsWrathAura := warrior.RegisterAura(core.Aura{
				ActionID:  core.ActionID{SpellID: 21887},
				Label:     "Warrior's Wrath",
				Duration:  time.Second * 10,
				MaxStacks: 2,
				OnInit: func(aura *core.Aura, sim *core.Simulation) {
					for _, spell := range warrior.Spellbook {
						if spell.Cost != nil && spell.Cost.CostType() == core.CostTypeRage && !spell.Flags.Matches(core.SpellFlagHelpful) {
							affectedSpells = append(affectedSpells, spell)
						}
					}
				},
				OnGain: func(aura *core.Aura, sim *core.Simulation) {
					aura.SetStacks(sim, aura.MaxStacks)
					for _, spell := range affectedSpells {
						spell.Cost.FlatModifier -= 2
					}
				},
				OnExpire: func(aura *core.Aura, sim *core.Simulation) {
					for _, spell := range affectedSpells {
						spell.Cost.FlatModifier += 2
					}
				},
				OnCastComplete: func(aura *core.Aura, sim *core.Simulation, spell *core.Spell) {
					if slices.Contains(affectedSpells, spell) {
						aura.RemoveStack(sim)
					}
				},
			})

			core.MakePermanent(warrior.RegisterAura(core.Aura{
				Label: "Warrior's Wrath Trigger",
				OnCastComplete: func(aura *core.Aura, sim *core.Simulation, spell *core.Spell) {
					if slices.Contains(affectedSpells, spell) {
						if sim.Proc(0.2, "Warrior's Wrath Trigger") {
							warriorsWrathAura.Activate(sim)
						}
					}
				},
			}))
		},
		// (4) Set: Increases the threat generated by Sunder Armor by 15%.
		4: func(agent core.Agent) {
			warrior := agent.(WarriorAgent).GetWarrior()
			warrior.RegisterAura(core.Aura{
				Label: "Battlegear of Wrath - Enhanced Sunder Armor",
				OnInit: func(aura *core.Aura, sim *core.Simulation) {
					warrior.SunderArmor.ThreatMultiplier *= 1.15
					warrior.SunderArmor.FlatThreatBonus *= 1.15
				},
			})
		},
		// (6) Set: Allows your Shield Block ability to block an additional attack. (Shield Reflection is
		// not implemented in this sim.)
		6: func(agent core.Agent) {
			warrior := agent.(WarriorAgent).GetWarrior()
			warrior.RegisterAura(core.Aura{
				Label: "Battlegear of Wrath - Shield Block",
				OnInit: func(aura *core.Aura, sim *core.Simulation) {
					if warrior.ShieldBlockAura != nil {
						warrior.ShieldBlockAura.MaxStacks += 1
					}
				},
			})
		},
		// (8) Set: 10% chance to parry the next attack after a block.
		8: func(agent core.Agent) {
			warrior := agent.(WarriorAgent).GetWarrior()
			actionID := core.ActionID{SpellID: 23548}

			parryAura := warrior.RegisterAura(core.Aura{
				ActionID: actionID,
				Label:    "Parry",
				Duration: time.Second * 10,
				OnGain: func(aura *core.Aura, sim *core.Simulation) {
					warrior.AddStatDynamic(sim, stats.Parry, 100*core.ParryRatingPerParryChance)
				},
				OnExpire: func(aura *core.Aura, sim *core.Simulation) {
					warrior.AddStatDynamic(sim, stats.Parry, -100*core.ParryRatingPerParryChance)
				},
				OnSpellHitTaken: func(aura *core.Aura, sim *core.Simulation, spell *core.Spell, result *core.SpellResult) {
					aura.Deactivate(sim)
				},
			})

			core.MakePermanent(warrior.RegisterAura(core.Aura{
				Label: "Parry Trigger Aura",
				OnSpellHitTaken: func(aura *core.Aura, sim *core.Simulation, spell *core.Spell, result *core.SpellResult) {
					if result.DidBlock() && sim.Proc(0.10, "Parry Proc") {
						parryAura.Activate(sim)
					}
				},
			}))

		},
	},
})

var ItemSetVindicatorsBattlegear = core.NewItemSet(core.ItemSet{
	Name: "Vindicator's Battlegear",
	Bonuses: map[int32]core.ApplyEffect{
		// (2) Set: Decreases the cooldowns of Intimidating and Challenging Shouts by 60 sec.
		2: func(agent core.Agent) {
			// Neither Intimidating Shout nor Challenging Shout (taunt) is implemented in the sim.
		},
		// (3) Set: Decreases the rage cost of Rend, Slam and Sunder Armor by 20%.
		3: func(agent core.Agent) {
			warrior := agent.(WarriorAgent).GetWarrior()
			warrior.RegisterAura(core.Aura{
				Label: "Vindicator's Battlegear - Rage Reduction",
				OnInit: func(aura *core.Aura, sim *core.Simulation) {
					warrior.Rend.Cost.Multiplier -= 20
					warrior.Slam.Cost.Multiplier -= 20
					warrior.SunderArmor.Cost.Multiplier -= 20
				},
			})
		},
		// (5) Set: Decrease the rage cost and cooldown of Thunder Clap and Whirlwind by 20%.
		5: func(agent core.Agent) {
			warrior := agent.(WarriorAgent).GetWarrior()
			warrior.RegisterAura(core.Aura{
				Label: "Vindicator's Battlegear - Thunder Clap and Whirlwind",
				OnInit: func(aura *core.Aura, sim *core.Simulation) {
					warrior.ThunderClap.Cost.Multiplier -= 20
					warrior.Whirlwind.Cost.Multiplier -= 20
					warrior.ThunderClap.CD.Duration = time.Duration(float64(warrior.ThunderClap.CD.Duration) * 0.8)
					warrior.Whirlwind.CD.Duration = time.Duration(float64(warrior.Whirlwind.CD.Duration) * 0.8)
				},
			})
		},
	},
})

///////////////////////////////////////////////////////////////////////////
//                            Phase 4 Item Sets - AQ
///////////////////////////////////////////////////////////////////////////

var ItemSetBattlegearOfHeroism = core.NewItemSet(core.ItemSet{
	Name: "Battlegear of Heroism",
	Bonuses: map[int32]core.ApplyEffect{
		// (2) Set: +10 Resistances/+200 Armor.
		2: func(agent core.Agent) {
			c := agent.GetCharacter()
			c.AddResistances(10)
			c.AddStat(stats.Armor, 200)
		},
		// (4) Set: Chance to heal for 88 to 132 when dealing or taking physical damage.
		4: func(agent core.Agent) {
			c := agent.GetCharacter()
			actionID := core.ActionID{SpellID: 27419}
			healthMetrics := c.NewHealthMetrics(core.ActionID{SpellID: 27419})

			core.MakeProcTriggerAura(&c.Unit, core.ProcTrigger{
				ActionID: actionID,
				Name:     "Warrior's Resolve",
				Callback: core.CallbackOnSpellHitDealt | core.CallbackOnSpellHitTaken,
				Outcome:  core.OutcomeLanded,
				ProcMask: core.ProcMaskMelee,
				PPM:      1,
				Handler: func(sim *core.Simulation, spell *core.Spell, _ *core.SpellResult) {
					c.GainHealth(sim, sim.Roll(88, 132), healthMetrics)
				},
			})
		},
		// (6) Set: +40 Attack Power.
		6: func(agent core.Agent) {
			c := agent.GetCharacter()
			c.AddStats(stats.Stats{
				stats.AttackPower:       40,
				stats.RangedAttackPower: 40,
			})
		},
		// (8) Set: +10 Resistances/+200 Armor.
		8: func(agent core.Agent) {
			c := agent.GetCharacter()
			c.AddResistances(10)
			c.AddStat(stats.Armor, 200)
		},
	},
})

///////////////////////////////////////////////////////////////////////////
//                            Phase 5 Item Sets - Naxx
///////////////////////////////////////////////////////////////////////////

