package mage

import (
	"slices"
	"time"

	"github.com/wowsims/classic/sim/core"
	"github.com/wowsims/classic/sim/core/stats"
)

///////////////////////////////////////////////////////////////////////////
//                            Classic Phase 1 - Molten Core
///////////////////////////////////////////////////////////////////////////

var ItemSetArcanistRegalia = core.NewItemSet(core.ItemSet{
	Name: "Arcanist Regalia",
	Bonuses: map[int32]core.ApplyEffect{
		// Decreases the magical resistances of your spell targets by 18.
		2: func(agent core.Agent) {
			c := agent.GetCharacter()
			c.AddStat(stats.SpellPenetration, 18)
		},
		// Increases the range of your spells by 3 yd.
		// Nothing to do: range has no mechanical effect in this sim.
		4: func(agent core.Agent) {
			// Nothing to do
		},
		// Decreases the threat generated by your spells by 15%.
		6: func(agent core.Agent) {
			mage := agent.(MageAgent).GetMage()
			mage.RegisterAura(core.Aura{
				Label:    "Subtlety",
				ActionID: core.ActionID{SpellID: 23545},
				Duration: core.NeverExpires,
				OnReset: func(aura *core.Aura, sim *core.Simulation) {
					mage.PseudoStats.ThreatMultiplier /= 1.15
				},
			})
		},
		// Reduces cooldown on your Evocation and Presence of Mind by 8 minutes.
		8: func(agent core.Agent) {
			mage := agent.(MageAgent).GetMage()
			mage.RegisterAura(core.Aura{
				Label: "Arcanist Evocation",
				OnInit: func(aura *core.Aura, sim *core.Simulation) {
					if mage.Evocation != nil {
						mage.Evocation.CD.Duration -= time.Minute * 8
					}
					// Nothing to do for Presence of Mind: it is not implemented on this server's talent tree.
				},
			})
		},
	},
})

///////////////////////////////////////////////////////////////////////////
//                            Phase 2 Item Sets - Dire Maul
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
//                            Phase 3 Item Sets - BWL
///////////////////////////////////////////////////////////////////////////

var ItemSetNetherwindRegalia = core.NewItemSet(core.ItemSet{
	Name: "Netherwind Regalia",
	Bonuses: map[int32]core.ApplyEffect{
		// Reduces the threat generated by your Scorch, Arcane Missiles, Fireball, and Frostbolt spells.
		2: func(agent core.Agent) {
			mage := agent.(MageAgent).GetMage()
			mage.RegisterAura(core.Aura{
				Label: "Friendly Nukes",
				OnInit: func(aura *core.Aura, sim *core.Simulation) {
					for _, spell := range mage.Spellbook {
						if spell.SpellCode == SpellCode_MageFireball || spell.SpellCode == SpellCode_MageArcaneMissilesTick {
							spell.FlatThreatBonus -= 20
						}
						if spell.SpellCode == SpellCode_MageScorch || spell.SpellCode == SpellCode_MageFrostbolt {
							spell.FlatThreatBonus -= 100
						}
					}
				},
			})
		},
		// Increases the radius of your Area of Effect spells by 2 yds.
		// Nothing to do: spell radius/AoE size has no mechanical effect in this sim.
		4: func(agent core.Agent) {
			// Nothing to do
		},
		// 5% chance after casting Arcane Missiles, Fireball, or Frostbolt that your next spell with a casting time under 10 seconds cast instantly.
		6: func(agent core.Agent) {
			mage := agent.(MageAgent).GetMage()
			actionID := core.ActionID{SpellID: 22008}

			affectedSpells := []*core.Spell{}
			netherwindFocusAura := mage.RegisterAura(core.Aura{
				Label:    "Netherwind Focus",
				ActionID: actionID,
				Duration: time.Second * 10,
				OnInit: func(aura *core.Aura, sim *core.Simulation) {
					for spellIdx := range mage.Spellbook {
						if spell := mage.Spellbook[spellIdx]; spell.DefaultCast.CastTime > 0 && spell.DefaultCast.CastTime <= 10*time.Second {
							affectedSpells = append(affectedSpells, spell)
						}
					}
				},
				OnGain: func(aura *core.Aura, sim *core.Simulation) {
					core.Each(affectedSpells, func(spell *core.Spell) {
						spell.CastTimeMultiplier -= 1
					})
				},
				OnExpire: func(aura *core.Aura, sim *core.Simulation) {
					core.Each(affectedSpells, func(spell *core.Spell) {
						spell.CastTimeMultiplier += 1
					})
				},
				OnCastComplete: func(aura *core.Aura, sim *core.Simulation, spell *core.Spell) {
					if !slices.Contains(affectedSpells, spell) {
						return
					}
					if spell.CurCast.CastTime > 0 { //Returns if you are midcast when your aura procs from landing to prevent instant consumption
						return
					}
					aura.Deactivate(sim)
				},
			})

			mage.RegisterAura(core.Aura{
				Label:    "Netherwind Focus - Proc Aura",
				Duration: core.NeverExpires,
				OnReset: func(aura *core.Aura, sim *core.Simulation) {
					aura.Activate(sim)
				},
				OnSpellHitDealt: func(aura *core.Aura, sim *core.Simulation, spell *core.Spell, result *core.SpellResult) {
					if spell.SpellCode == SpellCode_MageArcaneMissiles || spell.SpellCode == SpellCode_MageFireball || spell.SpellCode == SpellCode_MageFrostbolt {
						if sim.Proc(0.05, "Netherwind Focus Proc") {
							netherwindFocusAura.Activate(sim)
						}
					}
				},
			})
		},
		// Increases the damage and mana cost of your spells by 5%.
		8: func(agent core.Agent) {
			mage := agent.(MageAgent).GetMage()
			for _, schoolIdx := range []stats.SchoolIndex{stats.SchoolIndexArcane, stats.SchoolIndexFire, stats.SchoolIndexFrost} {
				mage.PseudoStats.SchoolDamageDealtMultiplier[schoolIdx] *= 1.05
				mage.PseudoStats.SchoolCostMultiplier[schoolIdx] += 5
			}
		},
	},
})

///////////////////////////////////////////////////////////////////////////
//                            Phase 4 Item Sets - ZG and AB
///////////////////////////////////////////////////////////////////////////

var ItemSetIllusionistsAttire = core.NewItemSet(core.ItemSet{
	Name: "Illusionist's Attire",
	Bonuses: map[int32]core.ApplyEffect{
		// Increases the effect of Arcane Intellect and Arcane Brilliance by 25%.
		// Handled in AddRaidBuffs (mage.go), added to Mind Mastery's bonus.
		2: func(agent core.Agent) {
			// Nothing to do
		},
		// Reduces the threat of your Flamestrike spell by 50%.
		3: func(agent core.Agent) {
			mage := agent.(MageAgent).GetMage()
			mage.RegisterAura(core.Aura{
				Label: "Improved Flamestrike Threat",
				OnInit: func(aura *core.Aura, sim *core.Simulation) {
					for _, spell := range mage.Spellbook {
						if spell.SpellCode == SpellCode_MageFlamestrike {
							spell.ThreatMultiplier *= 0.5
						}
					}
				},
			})
		},
		// Increases damage and healing done by magical spells and effects by up to 27.
		5: func(agent core.Agent) {
			c := agent.GetCharacter()
			c.AddStat(stats.SpellPower, 27)
		},
	},
})

///////////////////////////////////////////////////////////////////////////
//                            Phase 5 Item Sets - AQ
///////////////////////////////////////////////////////////////////////////

var ItemSetSorcerersRegalia = core.NewItemSet(core.ItemSet{
	Name: "Sorcerer's Regalia",
	Bonuses: map[int32]core.ApplyEffect{
		// +10 Resistances/+200 Armor.
		2: func(agent core.Agent) {
			c := agent.GetCharacter()
			c.AddResistances(10)
			c.AddStat(stats.Armor, 200)
		},
		// When struck in combat has a chance of freezing the attacker in place for 8 sec.
		// Nothing to do: this sim does not model incoming melee attackers being
		// crowd-controlled, so a defensive freeze proc has no mechanical effect.
		4: func(agent core.Agent) {
			// Nothing to do
		},
		// Increases damage and healing done by magical spells and effects by up to 23.
		6: func(agent core.Agent) {
			c := agent.GetCharacter()
			c.AddStat(stats.SpellPower, 23)
		},
		// +10 Resistances/+200 Armor.
		8: func(agent core.Agent) {
			c := agent.GetCharacter()
			c.AddResistances(10)
			c.AddStat(stats.Armor, 200)
		},
	},
})

///////////////////////////////////////////////////////////////////////////
//                            Phase 6 Item Sets - Naxx
///////////////////////////////////////////////////////////////////////////
