syntax = "proto3";
package proto;

option go_package = "./proto";

message PaladinTalents {
	// Holy
	int32 improved_seal_of_righteousness = 1;
	int32 divine_strength = 2;
	int32 divine_intellect = 3;
	int32 improved_lay_on_hands = 4;
	int32 aura_mastery = 5;
	int32 spiritual_focus = 6;
	int32 holy_power = 7;
	int32 shield_of_faith = 8;
	int32 divine_concentration = 9;
	bool inner_light = 10;
	int32 divine_grace = 11;
	int32 holy_grasp = 12;
	int32 illumination = 13;
	int32 unyielding_faith = 14;
	int32 lights_mercy = 15;
	int32 improved_purifying = 16;
	bool holy_shock = 17;
	int32 healing_light = 18;
	int32 searing_light = 19;
	bool holy_purge = 20;

	// Protection
	int32 improved_hammer_of_justice = 21;
	int32 toughness = 22;
	int32 shield_specialization = 23;
	int32 vindication = 24;
	int32 guardians_favor = 25;
	int32 redoubt = 26;
	int32 precision = 27;
	bool dominance = 28;
	int32 second_wind = 29;
	int32 improved_concentration_aura = 30;
	bool seal_of_fury = 31;
	int32 improved_defensive_auras = 32;
	int32 unbreakability = 33;
	int32 one_handed_weapon_specialization = 34;
	bool divine_protection = 35;
	bool holy_shield = 36;
	int32 improved_righteous_fury = 37;
	int32 morale = 38;
	int32 reckoning = 39;
	bool stoicism = 40;

	// Retribution
	int32 improved_judgement = 41;
	int32 conviction = 42;
	int32 improved_seal_of_the_crusader = 43;
	int32 deflection = 44;
	int32 pursuit_of_justice = 45;
	int32 divine_might = 46;
	int32 the_revenant = 47;
	int32 crusade = 48;
	bool seal_of_command = 49;
	int32 eye_for_an_eye = 50;
	int32 improved_retribution_aura = 51;
	int32 benediction = 52;
	int32 two_handed_weapon_specialization = 53;
	int32 improved_sanctity_aura = 54;
	bool sanctity_aura = 55;
	int32 vengeance = 56;
	bool repentance = 57;
	int32 blessed_strikes = 58;
	int32 codex_of_the_silver_hand = 59;
	bool inevitable_justice = 60;
}

enum Blessings {
	BlessingUnknown = 0;
	BlessingOfKings = 1;
	BlessingOfMight = 2;
	BlessingOfSalvation = 3;
	BlessingOfWisdom = 4;
	BlessingOfSanctuary = 5;
	BlessingOfLight = 6;
}

enum PaladinAura {
	NoPaladinAura = 0;
	SanctityAura = 1;
	DevotionAura = 2;
	RetributionAura = 3;
	ConcentrationAura = 4;
	FrostResistanceAura = 5;
	ShadowResistanceAura = 6;
	FireResistanceAura = 7;
}

enum PaladinSeal {
	NoSeal = 0;
	Righteousness = 1;
	Command = 2;
	reserved 3; // Seal of Martyrdom (Season of Discovery rune)
	reserved "Martyrdom";
	Fury = 4;
}

message PaladinOptions {
	PaladinSeal primarySeal = 1;
	PaladinAura aura = 2;
	bool IsUsingDivineStormStopAttack = 4;
	bool IsUsingJudgementStopAttack = 5;
	bool IsUsingCrusaderStrikeStopAttack = 6;

    bool righteousFury = 8;
    Blessings personalBlessing = 9;
}

message RetributionPaladin {
	message Rotation {
	}

	PaladinOptions options = 3;
}

message ProtectionPaladin {
	message Rotation {
	}

	PaladinOptions options = 3;
}

message HolyPaladin {
	message Rotation {
	}

	PaladinOptions options = 3;
}
