syntax = "proto3";
package proto;

option go_package = "./proto";

message ShamanTalents {
	// Elemental
	int32 storm_reach = 1;
	int32 elemental_warding = 2;
	int32 concussion = 3;
	int32 earths_grasp = 4;
	int32 convection = 5;
	int32 call_of_flame = 6;
	int32 reverberation = 7;
	bool sand_blast = 8;
	int32 elemental_focus = 9;
	int32 call_of_thunder = 10;
	int32 eye_of_the_storm = 11;
	int32 elemental_fury = 12;
	int32 elemental_devastation = 13;
	int32 improved_fire_totems = 14;
	bool elemental_mastery = 15;
	int32 lightning_mastery = 16;
	int32 elemental_precision = 17;
	int32 lightning_overlord = 18;
	int32 static_field = 19;
	bool earthquake = 20;

	// Enhancement
	int32 elemental_weapons = 21;
	bool earth_shield = 22;
	int32 ancestral_knowledge = 23;
	int32 toughness = 24;
	int32 guardian_totems = 25;
	int32 thundering_strikes = 26;
	int32 improved_elemental_shields = 27;
	int32 rockhide = 28;
	int32 flurry = 29;
	bool aftershock = 30;
	int32 improved_ghost_wolf = 31;
	int32 enhancing_totems = 32;
	int32 primal_endurance = 33;
	int32 weapon_mastery = 34;
	int32 improved_weapon_totems = 35;
	bool bloodlust = 36;
	int32 anticipation = 37;
	int32 armaments_of_storm = 38;
	int32 shamanism = 39;
	bool stormforged = 40;

	// Restoration
	int32 natures_guidance = 41;
	int32 tidal_mastery = 42;
	int32 spiritwalking = 43;
	int32 improved_healing_wave = 44;
	int32 totemic_mastery = 45;
	int32 nature_grace = 46;
	int32 natures_guardian = 47;
	bool tidal_barrier = 48;
	int32 totemic_focus = 49;
	int32 nature_focus = 50;
	int32 nature_spirit = 51;
	int32 tidal_focus = 52;
	int32 restorative_totems = 53;
	int32 ancestral_healing = 54;
	int32 purification = 55;
	bool natures_swiftness = 56;
	int32 focused_mind = 57;
	int32 healing_way = 58;
	int32 meditation = 59;
	bool cleansing_wave = 60;
}

enum EarthTotem {
	NoEarthTotem = 0;
	StrengthOfEarthTotem = 1;
	TremorTotem = 2;
	StoneskinTotem = 3;
}

enum AirTotem {
	NoAirTotem = 0;
	WindfuryTotem = 1;
	GraceOfAirTotem = 2;
}

enum FireTotem {
	NoFireTotem = 0;
	MagmaTotem = 1;
	SearingTotem = 2;
	FireNovaTotem = 3;
}

enum WaterTotem {
	NoWaterTotem = 0;
	ManaSpringTotem = 1;
	HealingStreamTotem = 2;
}

// Deprecated on 2024-02-08. Use APL totems instead
message ShamanTotems {
	// Not used here, but used by APL
	enum TotemType {
		TypeUnknown = 0;
		Earth = 1;
		Air = 2;
		Fire = 3;
		Water = 4;
	}

	EarthTotem earth = 1;
	AirTotem air = 2;
	FireTotem fire = 3;
	WaterTotem water = 4;

	// If set, will use mana tide when appropriate.
	bool use_mana_tide = 5;

	// If set, any time a 2-minute totem is about to expire, will recall and
	// replace all totems.
	bool recall_totems = 8;

	// If set will use fire totems as an MCD instead of manually controlling when to place them.
	bool use_fire_mcd = 9;

	// Bonus spell power for fire elemental snapshotting.
	int32 bonus_spellpower = 10;

	// Snapshot fire elemental using Tier 10 4 set bonus.
	bool enh_tier_ten_bonus = 11;
}

enum ShamanSyncType {
  NoSync = 0;
  SyncMainhandOffhandSwings = 1;
  DelayOffhandSwings = 2;
	Auto = 3;
}

message ElementalShaman {
	message Rotation {
	}

	// NextIndex: 6
	message Options {
	}
	Options options = 3;
}

message EnhancementShaman {
	message Rotation {
	}

	// NextIndex: 7
	message Options {
		ShamanSyncType sync_type = 3;
	}
	Options options = 3;
}

enum ShamanHealSpell {
	AutoHeal = 0;
	HealingWave = 1;
	LesserHealingWave = 2;
	ChainHeal = 3;
}

message RestorationShaman {
	message Rotation {
	}

	// NextIndex: 8
	message Options {
		int32 earth_shield_p_p_m = 5;
		ShamanTotems totems = 6 [deprecated=true];
	}
	Options options = 3;
}

message TankShaman {
	message Rotation {
	}

	message Options {
	}
	Options options = 1;
}
